//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace FlexImage.WebService.ControlSiteWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SiteControlServiceBinding", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class SiteControlWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkSiteControlOperationCompleted;
        
        private System.Threading.SendOrPostCallback closeSiteControlOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSuggestedCloseDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSuggestedOpenDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback openSiteControlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SiteControlWSService() {
            this.Url = global::FlexImage.WebService.Properties.Settings.Default.FlexImage_WSControlSite_ControlSiteWebReference_ControlWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkSiteControlCompletedEventHandler checkSiteControlCompleted;
        
        /// <remarks/>
        public event closeSiteControlCompletedEventHandler closeSiteControlCompleted;
        
        /// <remarks/>
        public event getSuggestedCloseDayCompletedEventHandler getSuggestedCloseDayCompleted;
        
        /// <remarks/>
        public event getSuggestedOpenDayCompletedEventHandler getSuggestedOpenDayCompleted;
        
        /// <remarks/>
        public event openSiteControlCompletedEventHandler openSiteControlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkSiteControlResponse", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
        public checkSiteControlResponse checkSiteControl([System.Xml.Serialization.XmlElementAttribute("checkSiteControl", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")] checkSiteControl checkSiteControl1) {
            object[] results = this.Invoke("checkSiteControl", new object[] {
                        checkSiteControl1});
            return ((checkSiteControlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void checkSiteControlAsync(checkSiteControl checkSiteControl1) {
            this.checkSiteControlAsync(checkSiteControl1, null);
        }
        
        /// <remarks/>
        public void checkSiteControlAsync(checkSiteControl checkSiteControl1, object userState) {
            if ((this.checkSiteControlOperationCompleted == null)) {
                this.checkSiteControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckSiteControlOperationCompleted);
            }
            this.InvokeAsync("checkSiteControl", new object[] {
                        checkSiteControl1}, this.checkSiteControlOperationCompleted, userState);
        }
        
        private void OncheckSiteControlOperationCompleted(object arg) {
            if ((this.checkSiteControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkSiteControlCompleted(this, new checkSiteControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("closeSiteControlResponse", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
        public closeSiteControlResponse closeSiteControl([System.Xml.Serialization.XmlElementAttribute("closeSiteControl", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")] closeSiteControl closeSiteControl1) {
            object[] results = this.Invoke("closeSiteControl", new object[] {
                        closeSiteControl1});
            return ((closeSiteControlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void closeSiteControlAsync(closeSiteControl closeSiteControl1) {
            this.closeSiteControlAsync(closeSiteControl1, null);
        }
        
        /// <remarks/>
        public void closeSiteControlAsync(closeSiteControl closeSiteControl1, object userState) {
            if ((this.closeSiteControlOperationCompleted == null)) {
                this.closeSiteControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseSiteControlOperationCompleted);
            }
            this.InvokeAsync("closeSiteControl", new object[] {
                        closeSiteControl1}, this.closeSiteControlOperationCompleted, userState);
        }
        
        private void OncloseSiteControlOperationCompleted(object arg) {
            if ((this.closeSiteControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.closeSiteControlCompleted(this, new closeSiteControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getSuggestedCloseDayResponse", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
        public getSuggestedCloseDayResponse getSuggestedCloseDay([System.Xml.Serialization.XmlElementAttribute("getSuggestedCloseDay", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")] getSuggestedCloseDay getSuggestedCloseDay1) {
            object[] results = this.Invoke("getSuggestedCloseDay", new object[] {
                        getSuggestedCloseDay1});
            return ((getSuggestedCloseDayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getSuggestedCloseDayAsync(getSuggestedCloseDay getSuggestedCloseDay1) {
            this.getSuggestedCloseDayAsync(getSuggestedCloseDay1, null);
        }
        
        /// <remarks/>
        public void getSuggestedCloseDayAsync(getSuggestedCloseDay getSuggestedCloseDay1, object userState) {
            if ((this.getSuggestedCloseDayOperationCompleted == null)) {
                this.getSuggestedCloseDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSuggestedCloseDayOperationCompleted);
            }
            this.InvokeAsync("getSuggestedCloseDay", new object[] {
                        getSuggestedCloseDay1}, this.getSuggestedCloseDayOperationCompleted, userState);
        }
        
        private void OngetSuggestedCloseDayOperationCompleted(object arg) {
            if ((this.getSuggestedCloseDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSuggestedCloseDayCompleted(this, new getSuggestedCloseDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getSuggestedOpenDayResponse", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
        public getSuggestedOpenDayResponse getSuggestedOpenDay([System.Xml.Serialization.XmlElementAttribute("getSuggestedOpenDay", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")] getSuggestedOpenDay getSuggestedOpenDay1) {
            object[] results = this.Invoke("getSuggestedOpenDay", new object[] {
                        getSuggestedOpenDay1});
            return ((getSuggestedOpenDayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getSuggestedOpenDayAsync(getSuggestedOpenDay getSuggestedOpenDay1) {
            this.getSuggestedOpenDayAsync(getSuggestedOpenDay1, null);
        }
        
        /// <remarks/>
        public void getSuggestedOpenDayAsync(getSuggestedOpenDay getSuggestedOpenDay1, object userState) {
            if ((this.getSuggestedOpenDayOperationCompleted == null)) {
                this.getSuggestedOpenDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSuggestedOpenDayOperationCompleted);
            }
            this.InvokeAsync("getSuggestedOpenDay", new object[] {
                        getSuggestedOpenDay1}, this.getSuggestedOpenDayOperationCompleted, userState);
        }
        
        private void OngetSuggestedOpenDayOperationCompleted(object arg) {
            if ((this.getSuggestedOpenDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSuggestedOpenDayCompleted(this, new getSuggestedOpenDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("openSiteControlResponse", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
        public openSiteControlResponse openSiteControl([System.Xml.Serialization.XmlElementAttribute("openSiteControl", Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")] openSiteControl openSiteControl1) {
            object[] results = this.Invoke("openSiteControl", new object[] {
                        openSiteControl1});
            return ((openSiteControlResponse)(results[0]));
        }
        
        /// <remarks/>
        public void openSiteControlAsync(openSiteControl openSiteControl1) {
            this.openSiteControlAsync(openSiteControl1, null);
        }
        
        /// <remarks/>
        public void openSiteControlAsync(openSiteControl openSiteControl1, object userState) {
            if ((this.openSiteControlOperationCompleted == null)) {
                this.openSiteControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnopenSiteControlOperationCompleted);
            }
            this.InvokeAsync("openSiteControl", new object[] {
                        openSiteControl1}, this.openSiteControlOperationCompleted, userState);
        }
        
        private void OnopenSiteControlOperationCompleted(object arg) {
            if ((this.openSiteControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.openSiteControlCompleted(this, new openSiteControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class checkSiteControl {
        
        private long siteIdField;
        
        private bool siteIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long siteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siteIdSpecified {
            get {
                return this.siteIdFieldSpecified;
            }
            set {
                this.siteIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class openSiteControlResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class openSiteControl {
        
        private long usrIdField;
        
        private bool usrIdFieldSpecified;
        
        private long stationIdField;
        
        private bool stationIdFieldSpecified;
        
        private long siteIdField;
        
        private bool siteIdFieldSpecified;
        
        private System.DateTime controlDateField;
        
        private bool controlDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long usrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrIdSpecified {
            get {
                return this.usrIdFieldSpecified;
            }
            set {
                this.usrIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stationIdSpecified {
            get {
                return this.stationIdFieldSpecified;
            }
            set {
                this.stationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long siteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siteIdSpecified {
            get {
                return this.siteIdFieldSpecified;
            }
            set {
                this.siteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime controlDate {
            get {
                return this.controlDateField;
            }
            set {
                this.controlDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool controlDateSpecified {
            get {
                return this.controlDateFieldSpecified;
            }
            set {
                this.controlDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class getSuggestedOpenDayResponse {
        
        private System.DateTime returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class getSuggestedOpenDay {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class getSuggestedCloseDayResponse {
        
        private System.DateTime returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class getSuggestedCloseDay {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class closeSiteControlResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class closeSiteControl {
        
        private long usrIdField;
        
        private bool usrIdFieldSpecified;
        
        private long stationIdField;
        
        private bool stationIdFieldSpecified;
        
        private long siteIdField;
        
        private bool siteIdFieldSpecified;
        
        private System.DateTime controlDateField;
        
        private bool controlDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long usrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrIdSpecified {
            get {
                return this.usrIdFieldSpecified;
            }
            set {
                this.usrIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stationIdSpecified {
            get {
                return this.stationIdFieldSpecified;
            }
            set {
                this.stationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long siteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siteIdSpecified {
            get {
                return this.siteIdFieldSpecified;
            }
            set {
                this.siteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime controlDate {
            get {
                return this.controlDateField;
            }
            set {
                this.controlDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool controlDateSpecified {
            get {
                return this.controlDateFieldSpecified;
            }
            set {
                this.controlDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.service.ws.mdi.flexdoc.com.br/")]
    public partial class checkSiteControlResponse {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void checkSiteControlCompletedEventHandler(object sender, checkSiteControlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkSiteControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkSiteControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public checkSiteControlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((checkSiteControlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void closeSiteControlCompletedEventHandler(object sender, closeSiteControlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class closeSiteControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal closeSiteControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public closeSiteControlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((closeSiteControlResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getSuggestedCloseDayCompletedEventHandler(object sender, getSuggestedCloseDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSuggestedCloseDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSuggestedCloseDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getSuggestedCloseDayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getSuggestedCloseDayResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getSuggestedOpenDayCompletedEventHandler(object sender, getSuggestedOpenDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSuggestedOpenDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSuggestedOpenDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getSuggestedOpenDayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getSuggestedOpenDayResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void openSiteControlCompletedEventHandler(object sender, openSiteControlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class openSiteControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal openSiteControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public openSiteControlResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((openSiteControlResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591